MovieBoard/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_board_app.urls')),
    path('', include('create_user_app.urls')),

    # for login and registration
    # accounts/login - automatically redirect to a login.html page under template >> registration
    path('accounts/', include ('django.contrib.auth.urls'))
]

create_user_app/urls.py
from django.urls import path, include
from django.conf.urls import url
from rest_framework.routers import DefaultRouter
from create_user_app import create_user_api
from create_user_app import views

app_name = 'create_user'

urlpatterns = [
    # /movie_board/
    # Create movies
    path('create_movie/', views.CreateMovie.as_view(), name = 'create_movie'),

    # Registration
    path('register/', views.register, name = 'register')
]

movie_board_app/urls.py
from django.urls import path, include
from django.conf.urls import url
from rest_framework.routers import DefaultRouter
from movie_board_app import movie_list_api # importing API
from movie_board_app import views # importing views
from create_user_app import create_user_api # importing views

app_name = 'movie_board'

urlpatterns = [
    # /
    path('',                views.MovieBoardView.as_view(), name = 'home'),
    path('movie_list_api/', movie_list_api.MovieBoardList.as_view(), name = 'movie_board'),

    # UpVote
    path('upvote_movie/<movie_id>', views.UpVoteView.as_view(), name = 'upvote_movie'),
    path('upvote_movie_api/', movie_list_api.UpVoteMovie.as_view(), name = 'upvote_movie_api'),

    # Get third party score
    path('score_api/', movie_list_api.ThirdPartyRatings.as_view(), name = 'score_api'),
]

create_user_app/models.py
from django.db import models

class Recommender(models.Model):
    first_name    = models.CharField(max_length = 20)
    last_name     = models.CharField(max_length = 20)


    def __str__(self):
        # return str(self.pk) + " | " + self.first_name + "_" + self.last_name

        # The MovieBoardSerializer is returning the format set in this string
        return self.first_name + " " + self.last_name

movie_board_app/models.py
from django.conf import settings
from django.db import models
# from create_user_app import models as create_user_app_models


class Genre(models.Model):
    genre_type    = models.CharField(max_length = 20)

    def __str__(self):
        return str(self.pk) + " | " + self.genre_type


class Movie(models.Model):
    # Ele cria uma coluna album que, na verdade, eh o primary key da classe Album
    # on_delete = models.CASCADE --  quando o album for deletado, deletar também todas as musicas associadas a ele
    # recommender            = models.ForeignKey(create_user_app_models.Recommender, on_delete = models.CASCADE)
    # recommender gets from the User model
    recommender            = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    movie_title            = models.CharField(max_length = 50, default = '')
    youtube_trailer_link   = models.CharField(max_length = 250, default = '')
    genre                  = models.ForeignKey(Genre, on_delete = models.CASCADE)
    recommendee_first_name = models.CharField(max_length = 50, default = '')
    recommendee_last_name  = models.CharField(max_length = 50, default = '')
    vote_count             = models.IntegerField(default = 0)
    imdb_score             = models.CharField(max_length = 10, default = '')

    def __str__(self):
        return  str(self.pk) + " | " + self.recommender.first_name + " - " + self.movie_title

create_user_app/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render, redirect

import requests

# to work with HTML template
from django.template import loader

# Importing rest_framework
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import viewsets

from create_user_app.create_user_api import UserList,GenreList
from movie_board_app.views import MovieBoardView

# ThirdParty Scoring
from movie_board_app.movie_list_api import ThirdPartyRatings

# Login and registration form
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login



def index(request):
    return render(request, 'create_user_app/index.html')


def register(request):
    if request.method == 'POST':
        registration_form = UserCreationForm(request.POST)
        if registration_form.is_valid():
            registration_form.save() # save the new user to the database

             # authenticating the user
            username = registration_form.cleaned_data['username']
            password = registration_form.cleaned_data['password1'] # password1 is the first password field

            user = authenticate(username = username, password = password)
            # After authenticate, login the recently created user
            login(request, user)
            # Once loggedin, send to home page
            return MovieBoardView().get(request)
    else:
        registration_form = UserCreationForm()
    context = {
        'registration_form': registration_form
    }

    return render(request, 'registration/register.html', context)




class CreateMovie(APIView):
    def get(self, request):

        # If the user is authenticade, they can create a movie
        current_user = request.user
        if current_user.is_authenticated:
            all_genre = GenreList.get_genre_list()

            template = loader.get_template('create_user_app/create_movie.html')
            genre_context = {
                "genre_list": all_genre
            }

            # return render(request, 'create_user_app/create_user.html')
            return HttpResponse(template.render(genre_context, request))
        else:
            return register(request)


    def post(self, request):

        create_movie_requested = request.data # json format

        # Adding the ThirdParty ratings
        third_party_score = ThirdPartyRatings.get_third_party_score(request.data['movie_title'])

        # Getting the authenticated current user information
        # Will be used as recommender
        current_user = request.user
        if current_user.is_authenticated:
            print('user IS Autenticated')
            print(current_user)
        else:
            print('Usuario não autenticado')

        create_movie_data =  {
        "movie_title":            request.data['movie_title'],
        "youtube_trailer_link":   request.data['youtube_trailer_link'],
        "recommendee_first_name": request.data['recommendee_first_name'],
        "recommendee_last_name":  request.data['recommendee_last_name'],
        "vote_count":             0, # start with 0 votes
        "imdb_score":             third_party_score,
        "recommender":            current_user.id,
        "genre":                  request.data['genre']

        }


        URL = "http://127.0.0.1:8000/movie_list_api/"
        r = requests.post(url = URL, data = create_movie_data)

        # After creating a movie, goes to the movieboard list / home
        return MovieBoardView().get(request)

movie_board_app/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render

import requests

# to work with HTML template
from django.template import loader

# Importing rest_framework
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import viewsets




class MovieBoardView(APIView):

    def get(self, request):
        URL = "http://localhost:8000/movie_list_api/"
        r = requests.get(url = URL)

        # extracting data in json format
        movie_list_data = r.json()
        template = loader.get_template('movie_board_app/home.html')

        context = {
            'movie_list_data': movie_list_data
        }
        # No Response, always pass the request
        return HttpResponse(template.render(context, request))

class UpVoteView(APIView):
    # update ou patch
    def post(self, request, movie_id):

        data =  {
        "movie_primary_key": movie_id
        }

        URL = "http://localhost:8000/upvote_movie_api/"
        r = requests.post(url = URL, data = data)

        return MovieBoardView().get(request)

create_user_app/templates/create_user_app/create_movie.html
<body style="background-color: #0c343d;
             font-family: arial;
             color: white">


<h1 style = "color:#ffd966">Recommend a movie</h1>



<!-- Submit Movie -->
<form action = "{% url 'create_user:create_movie' %}" method = "POST">
  {% csrf_token %}


  <style>
    input[type=text] {
          border: 1px solid #a2c4c9;
          border-radius: 4px;
          width: 250px;
          padding: 10px;
          background-color: #0e3942;
          color: white;
          }
  </style>


  <label>Movie Title:</label><br>
  <input type = "text" name="movie_title">
  <br>
  <br>

  <label>Youtube Trailer link:</label><br>
  <input type = "text" name="youtube_trailer_link">
  <br>
  <br>

  <label>Recipient Name:</label><br>
  <input type = "text" name="recommendee_first_name">
  <br>
  <br>

  <label>Recipient Last Name:</label><br>
  <input type = "text" name="recommendee_last_name">
  <br>
  <br>

  <!-- <label>Genre:</label><br> -->
  <!-- <input type = "text" id="1" name="genre_test"><br><br> -->

  <label>Genre:</label>
  <br>

  <select name="genre">

    {% for genre in genre_list %}
    <option value="{{genre.id}}">{{genre.genre_type}}</option>
    {% endfor %}

  </select>
  <br>
  <br>



  <style>
    button {
          color:#ffd966;
          border: 1px solid #ffd966;
          background-color: Transparent;
          padding: 7px
          }
  </style>

  <button type="submit" name="add_recommendation">+ Add Recommendation</button>

  <!-- <input type = "submit" value = "+ Add Recommendations"/> -->
</form>



</body>

movie_board_app/templates/movie_board_app/home.html
<head>
      <!-- Description on the Broser tab -->
      <title>MovieBoard</title>

</head>


{% if user.is_authenticated %}
    <p style = "color:#ffd966">Hello {{user.username}}</p>
{% else %}

{% endif%}




<!-- UpVote buttom CSS -->
<style type="text/css">
    #submit {
      background-color: #0c343d;
      padding: .5em;
      border-radius: 6px;
      color: white;
    }
    #submit:hover {
      background: #134f5c;
      box-shadow: 0px 0px 1px #777;
      color: white
    }
</style>


<!-- Table CSS -->
<style type="text/css">
	.TFtable{
		border-collapse:collapse;
    color: white;
    font-family: arial;
    width:95%
	}
	.TFtable td{
		padding:10px; border:#134f5c 1px solid;
	}
	/* provide some minimal visual accomodation for IE8 and below */
	.TFtable tr{
		background: #b8d1f3;
	}
	/*  Define the background color for all the ODD background rows  */
	.TFtable tr:nth-child(odd){
		background: #0c343d;
	}
	/*  Define the background color for all the EVEN background rows  */
	.TFtable tr:nth-child(even){
		background: #0e3942;
	}
</style>


<!-- Change background color of part of the header -->
<style>
  span {
  background-color: #ffd966;
  color: #0c343d
}
</style>



<body style="background-color: #0c343d;
             font-family: arial;">



<h1 style = "color: #ffd966;
             position: relative;
             left: 3%;
             top: 5%">Movie <span>Board</span></h1>


<!-- Link para create user / create movie page -->
<a href = "{% url 'create_user:create_movie' %}"
   style="color: #ffd966;
          position: relative;
          left: 88%;
          border: 1px solid #ffd966;
          padding: 7px;
          text-decoration:none;
          font-size:11px"> + Add Recommendation </a>

   <!-- Table margem from left to right -->
    <div style = "position:relative; left: 3%; top: 5%">

          <table class="TFtable">

                <!-- Table Header -->
                <tr style = "font-size:15px; background-color: #134f5c; height: 50px; border: 1px solid #134f5c;">

                      <!-- <th>Up Vote</th> -->
                      <th>Votes</th>
                      <th>Movie Title</th>
                      <th>Ratings</th>
                      <th>Genre</th>
                      <th>Trailer</th>
                      <th>From</th>
                      <th>To</th>

                </tr>

                <!-- Table Data 👍 🤘 ↑	⬆ -->
                {% for movie_list in movie_list_data %}
                <!-- TROCAR AQUI A COR ALTERNADA DAS LINHAS DA TABELA -->

                {% with name="#0e3942" %}
                <tr style = "font-size:11px">
                {% endwith %}

                      <td style="text-align:center">

                          <form action="{% url 'movie_board:upvote_movie' movie_list.id %}" method="POST">
                              {% csrf_token %}
                              {{movie_list.vote_count}}
                              <button name="upvote"
                                      type="submit"
                                      id = "submit"
                                      style = "margin-left:12px"> ▲ </button> <!-- id = "submit" references the CSS style -->
                          </form>

                      </td>
                      <!-- <td>{{movie_list.vote_count}}   </td> -->
                      <td>{{movie_list.movie_title}}  </td>
                      <td>{{movie_list.imdb_score}}   </td>
                      <td>{{movie_list.genre}}        </td>
                      <td><a href = "{{movie_list.youtube_trailer_link}}" style="color:white; text-decoration:none">link</a></td>
                      <td>{{movie_list.recommender}}  </td>
                      <td>{{movie_list.recommendee_first_name}} {{movie_list.recommendee_last_name}}</td>

                </tr>
                {% endfor %}

          </table>

    </div>


</body>